### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by PabloCastellano** [JulienPalard/ansible-nginx-letsencrypt#1]
Hi @JulienPalard, would you mind releasing the current version as 1.0.0 or something? This way it can be pinned correctly in the requirements.

Thanks for sharing this project. I have found it extremely useful!

**Comment by JulienPalard** [comment]
I just tried by Ansible Galaxy want to list my private orgs in github, I'm not OK with that:

```
Organizations and teams
Read-only access

This application will be able to read your organization, team membership, and private project boards. 
```

so I won't be able to do further releases on Ansible Galaxy.

Feel free to fork the project, I'm archiving it.
